### ISSUE TITLE
[Improvement]: Enabling Edit Access

### ISSUE THREAD

**Issue by cancan101** [pimcore/perspective-editor#167]
### Improvement description

How do I enable edit access (ie actually using this Bundle)? By default, "Add Perspective", etc are grayed out:
![Image](https://github.com/user-attachments/assets/7be2042a-92d8-4c05-b22b-837c56c26f75)
[the docs say](https://github.com/pimcore/perspective-editor/blob/1.x/doc/01_Installation.md#bundle-installation):
>Also, make sure, that customviews.php and perspectives.php files are writeable for php. 

but I am told that is out of date: https://github.com/orgs/pimcore/discussions/17862#discussioncomment-11438228

Setting `APP_DEBUG=true` looks to work, but that does not seem ideal for production system.

**Comment by cancan101** [comment]
I solved this with:
```yaml
  config_location:
      perspectives:
        write_target:
          type: 'settings-store'
```
which allows reading yaml files and writing to the `settings-store`.
